version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.5.0
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: db-migrate
    versions:
    - 0.11.12
  - dependency-name: db-migrate-mysql
    versions:
    - 2.1.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: winston
    versions:
    - 3.3.3
  - dependency-name: bcrypt
    versions:
    - 5.0.0
  - dependency-name: dotenv
    versions:
    - 8.2.0
  - dependency-name: mysql
    versions:
    - 2.18.1
